name: Django CI with Docker

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3   # ✅ 여기 맞게 수정

    - name: Set up Python
      uses: actions/setup-python@v3         # ✅ Python 세팅은 따로
      with:
        python-version: '3.10'

    - name: Build Docker image
      run: |
        docker build -t django-test-image .

    - name: Run tests inside Docker container
      run: |
        docker run --rm django-test-image python manage.py test
