name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Save SSH Key (no ~/.ssh)
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > id_rsa
          chmod 600 id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> known_hosts

      - name: Decode and Upload .env to EC2
        run: |
          echo "${{ secrets.EC2_CONTENT_B64 }}" | base64 -d > .env
          scp -i id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=known_hosts .env ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/deploy_test/dockerproject/.env

      - name: Deploy to EC2
        run: |
          ssh -i id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=known_hosts ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'ENDSSH'
            cd ~/deploy_test/dockerproject
            git pull origin main
            docker build -t django-docker-app .
            docker stop django-app || true
            docker rm django-app || true
            docker run -d -p 8000:8000 --env-file .env --name django-app django-docker-app
          ENDSSH
